/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rental_skuter.User;

import database.DataSkuter;
import database.db_connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author dimas
 */
public class Sewa extends javax.swing.JFrame { 
    
    ResultSet rs;
    db_connection con;
    String id;
    String merek;
    String tipe;
    String tahun;
    String harga;
    String status;
    
    public Sewa() {
        con =new db_connection(new database.parameter().HOST_DB,new database.parameter().USERNAME_DB,new database.parameter().PASSWORD_DB);
        initComponents();
        data_skuter();
        
        harga_sewa.disable();
        submit_sewa.disable();
        total_harga.disable();
        uang_bayar.disable();
    }

    String nama_user;
    public void user_cr(String nama){
        nama_user = nama;
        hello_user.setText("Selamat datang, "+nama);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        hello_user = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data_skuter = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        id_skuter = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        durasi_sewa = new javax.swing.JTextField();
        harga_sewa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        submit_sewa = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        total_harga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        uang_bayar = new javax.swing.JTextField();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hello_user.setText("Selamat datang, {user}");

        data_skuter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(data_skuter);

        jLabel1.setText("ID Skuter yang ingin disewa");

        id_skuter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_skuterKeyTyped(evt);
            }
        });

        jLabel2.setText("Durasi sewa (jam)");

        harga_sewa.setEditable(false);

        jLabel3.setText("Harga sewa");

        submit_sewa.setText("Sewa Skuter");
        submit_sewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submit_sewaMouseClicked(evt);
            }
        });
        submit_sewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_sewaActionPerformed(evt);
            }
        });

        jButton2.setText("Hitung harga sewa");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel4.setText("Total harga");

        total_harga.setEditable(false);

        jLabel5.setText("Uang bayar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hello_user)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(id_skuter, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(harga_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(durasi_sewa, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(submit_sewa))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(uang_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hello_user)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(id_skuter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(harga_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(durasi_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uang_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit_sewa)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_sewaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submit_sewaMouseClicked
        
    }//GEN-LAST:event_submit_sewaMouseClicked
    
    private void id_skuterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_skuterKeyTyped
        
    }//GEN-LAST:event_id_skuterKeyTyped

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try{
            rs = con.querySelectAll("data_skuter", "id='" + id_skuter.getText() + "' and status='Tersedia'");
            while(rs.next()){
                id = rs.getString("id");
                merek = rs.getString("merek");
                tipe = rs.getString("tipe");
                tahun = rs.getString("tahun");
                harga = rs.getString("harga");
                status = rs.getString("status");
            }
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data");
        }

        if(id == null){
            JOptionPane.showMessageDialog(this, "Skuter tidak tersedia");
        }
        
        int durasi = Integer.parseInt(durasi_sewa.getText());
        int _harga = Integer.parseInt(harga);
        int total = durasi * _harga;
        
        harga_sewa.setText(""+_harga);
        total_harga.setText("Rp "+total);
        
        submit_sewa.setEnabled(true);
        uang_bayar.setEnabled(true);
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void submit_sewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_sewaActionPerformed
        peminjaman_skuter();
        data_skuter();
    }//GEN-LAST:event_submit_sewaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Sewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable data_skuter;
    private javax.swing.JTextField durasi_sewa;
    private javax.swing.JTextField harga_sewa;
    private javax.swing.JLabel hello_user;
    private javax.swing.JTextField id_skuter;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submit_sewa;
    private javax.swing.JTextField total_harga;
    private javax.swing.JTextField uang_bayar;
    // End of variables declaration//GEN-END:variables

    private void data_skuter(){
        String namaKolom[] = {"id","merek","tipe","tahun","harga","status"};
        rs=con.querySelect(namaKolom,"data_skuter");
        data_skuter.setModel(new DataSkuter(rs));
        
    }

    private void peminjaman_skuter() {
        if(id != null){
            if(status.contains("Keluar")){
                JOptionPane.showMessageDialog(this, "Skuter tidak bisa disewakan");
            }else{
                try {
                    if(Integer.parseInt(uang_bayar.getText()) < Integer.parseInt(harga)){
                        JOptionPane.showMessageDialog(this, "Uang pembayaran kurang!");
                    }else{
                        if( !durasi_sewa.getText().isEmpty() && !uang_bayar.getText().isEmpty()){
                        String kolom[] = {"nama_penyewa","merek","tipe","tahun","harga"};
                        String isi[] = { nama_user, merek,tipe, tahun, harga_sewa.getText()};

                        System.out.println( con.queryInsert("penyewa",kolom,isi));

//                        JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
                        String s_kolom[] = {"status"};
                        String s_isi[] = {"Keluar"};
                        con.queryUpdate("data_skuter", s_kolom, s_isi,"id='"+id+"'");
                        id_skuter.setText("");
                        durasi_sewa.setText("");
                        uang_bayar.setText("");
                        harga_sewa.disable();
                        submit_sewa.setEnabled(false);
                        total_harga.disable();
                        uang_bayar.disable();
                        JOptionPane.showMessageDialog(this, "Skuter telah disewakan");
                        }else{
                            JOptionPane.showMessageDialog(this, "Data isian ada yang kosong");
                        }
                    }
                     
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error input data");
                    System.out.println("salah");
                }
                
            }
        }
        
        
        
    }
    
}
