/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rental_skuter.Admin;

/**
 *
 * 
 */
public class Dashboard extends javax.swing.JFrame {

    String nama_;
    public Dashboard() {
        initComponents();
    }

    public void admin_cr(String nama, String status){
        nama_ = nama;
        hello_admin.setText("Selamat datang, "+ this.nama_);
        status_label.setText("Status: "+status);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        hello_admin = new javax.swing.JLabel();
        status_label = new javax.swing.JLabel();
        tambah_pengguna = new javax.swing.JButton();
        tambah_skuter = new javax.swing.JButton();
        daftar_skuter = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hello_admin.setText("Selamat datang, {user}");

        status_label.setText("Status: Admin");

        tambah_pengguna.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tambah_pengguna.setText("Tambah Pengguna");
        tambah_pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_penggunaActionPerformed(evt);
            }
        });

        tambah_skuter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tambah_skuter.setText("Tambah Skuter");
        tambah_skuter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambah_skuterMouseClicked(evt);
            }
        });

        daftar_skuter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        daftar_skuter.setText("Daftar Skuter");
        daftar_skuter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftar_skuterMouseClicked(evt);
            }
        });
        daftar_skuter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftar_skuterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hello_admin)
                            .addComponent(status_label)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tambah_pengguna, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tambah_skuter)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(daftar_skuter)))
                                .addGap(16, 16, 16)))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hello_admin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status_label)
                .addGap(58, 58, 58)
                .addComponent(tambah_pengguna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tambah_skuter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(daftar_skuter)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambah_skuterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah_skuterMouseClicked
        dispose();
        new TambahSkuter().setVisible(true);
    }//GEN-LAST:event_tambah_skuterMouseClicked

    private void daftar_skuterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftar_skuterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_daftar_skuterMouseClicked

    private void daftar_skuterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftar_skuterActionPerformed
        dispose();
        new DaftarSkuter().setVisible(true);
    }//GEN-LAST:event_daftar_skuterActionPerformed

    private void tambah_penggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_penggunaActionPerformed
        dispose();
        new TambahPengguna().setVisible(true);
    }//GEN-LAST:event_tambah_penggunaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton daftar_skuter;
    private javax.swing.JLabel hello_admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel status_label;
    private javax.swing.JButton tambah_pengguna;
    private javax.swing.JButton tambah_skuter;
    // End of variables declaration//GEN-END:variables
}
