/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rental_skuter;

import database.db_connection;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import rental_skuter.Admin.Dashboard;
import rental_skuter.Admin.TambahSkuter;
import rental_skuter.User.Sewa;
/**
 *
 * @author dimas
 */
public class Home extends javax.swing.JFrame {

    ResultSet rs;
    db_connection con;
    String id_user;
    String hak;
    String nama;
    boolean isLogin;
    public Home() {
        con = new db_connection(new database.parameter().HOST_DB, new database.parameter().USERNAME_DB, new database.parameter().PASSWORD_DB);
        setLocationRelativeTo(null);
        
        initComponents();
        
        password_label.setVisible(false);
        password_field.setVisible(false);
        email_label.setVisible(false);
        email_field.setVisible(false);
        submit_login_button.setVisible(false);
        
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);
    }
    
    void showLoginForm(String label){
        password_label.setVisible(true);
        password_field.setVisible(true);
        email_label.setText(label);
        email_label.setVisible(true);
        email_field.setVisible(true);
        submit_login_button.setVisible(true);
    }
    
    void loginInfo(String label, boolean check){
        if(!check){
            JOptionPane.showMessageDialog(null, label, "Login", JOptionPane.DEFAULT_OPTION);
        }else{
            JOptionPane.showMessageDialog(null, "Anda login menggunakan "+label, "Login", JOptionPane.DEFAULT_OPTION);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        submit_login_button = new javax.swing.JButton();
        email_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        password_field = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        login_with_instagram = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        login_with_google = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("LOGIN");

        email_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_fieldActionPerformed(evt);
            }
        });

        submit_login_button.setText("Login");
        submit_login_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submit_login_buttonMouseClicked(evt);
            }
        });

        email_label.setText("Email");

        password_label.setText("Password");

        password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_fieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Login menggunakan");

        login_with_instagram.setForeground(new java.awt.Color(51, 51, 255));
        login_with_instagram.setText("INSTAGRAM");
        login_with_instagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_with_instagramMouseClicked(evt);
            }
        });

        jLabel4.setText("Atau");

        login_with_google.setForeground(new java.awt.Color(51, 51, 255));
        login_with_google.setText("GOOGLE");
        login_with_google.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_with_googleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(email_label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(submit_login_button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(login_with_instagram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(login_with_google)
                                .addGap(16, 16, 16))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(email_field)
                                .addComponent(password_label)
                                .addComponent(password_field, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel2)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(email_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_label)
                .addGap(3, 3, 3)
                .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(submit_login_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_with_instagram)
                    .addComponent(jLabel4)
                    .addComponent(login_with_google))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_fieldActionPerformed

    private void password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_fieldActionPerformed

    private void login_with_instagramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_with_instagramMouseClicked
        showLoginForm("Email Instagram");
    }//GEN-LAST:event_login_with_instagramMouseClicked

    private void login_with_googleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_with_googleMouseClicked
        showLoginForm("Email Google");
    }//GEN-LAST:event_login_with_googleMouseClicked

    private void submit_login_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submit_login_buttonMouseClicked
        boolean check = false;
        if(email_field.getText().isEmpty()){
            loginInfo("Tidak boleh kosong!", check);
        }else{
            if(password_field.getText().isEmpty()){
                loginInfo("Tidak boleh kosong!", check);
            }else{
                try {
                    rs = con.querySelectAll("users_google", "email='" + email_field.getText() + "' and password='" + password_field.getText() + "'");
                    while (rs.next()) {
                        id_user = rs.getString("id");
                        hak = rs.getString("status");
                        nama = rs.getString("nama");
                    }
                } catch (SQLException ex) {
                }

                if (id_user != null) {
                    check = true;
                    this.dispose();
                    if (hak.equals("Admin")) {
                        JOptionPane.showMessageDialog(this, "Login Berhasil");
                        admin(nama, hak);
                    } else {
                        JOptionPane.showMessageDialog(this, "Login Berhasil");
                        user(nama);
                    }

                    isLogin = true;
                } else {
                    JOptionPane.showMessageDialog(this, "Login Gagal, Coba Lagi!!");
                }
                
//                if(email_label.getText() == "Email"){
//                  loginInfo("Google", check);
//              }else if(email_label.getText() == "Username"){
//                  loginInfo("Instagram", check);
//              }   
//                    
            }   
        }
    }//GEN-LAST:event_submit_login_buttonMouseClicked
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    public void admin(String nama, String status) {
        Dashboard d = new Dashboard();
        d.admin_cr(nama, status);
        d.setVisible(true);
    }

    public void user(String email) {
        Sewa s = new Sewa();
        s.user_cr(email);
        s.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email_field;
    private javax.swing.JLabel email_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel login_with_google;
    private javax.swing.JLabel login_with_instagram;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JLabel password_label;
    private javax.swing.JButton submit_login_button;
    // End of variables declaration//GEN-END:variables
}
